### PR TITLE
Add the emoji version 15.0 to `emoji-mart/data`

### PR DESCRIPTION
**Pull request by vemonet**
Hi @EtienneLem I upgraded the dependencies in the `emoji-mart/data` `package.json`, added version 15 to the list of emojis versions built, and run the build to add emoji version 15.0 to the package

It adds a few new emojis like 🫎 🪿 🫏: https://emojipedia.org/emoji-15.0/

Thanks a lot

### CODE REVIEW

**Review by gomjellie — CHANGES_REQUESTED** [review]
Following codes need to be changed: 

https://github.com/missive/emoji-mart/blob/d29728f7b4e295e46f9b64aa80335aa4a3c15b8e/packages/emoji-mart/src/components/Picker/PickerProps.ts#L21-L22 

```diff
-    value: 14,
-    choices: [1, 2, 3, 4, 5, 11, 12, 12.1, 13, 13.1, 14],
+    value: 15,
+    choices: [1, 2, 3, 4, 5, 11, 12, 12.1, 13, 13.1, 14, 15],
```

https://github.com/missive/emoji-mart/blob/d29728f7b4e295e46f9b64aa80335aa4a3c15b8e/packages/emoji-mart/src/helpers/native-support.ts#L2-L4

```diff
const VERSIONS = [
+  { v: 15, emoji: '🫨' },
  { v: 14, emoji: '🫠' },
``` 

wish this PR be merged quickly 😄

**Comment by marlon12796** [comment]
Why didn't it merge?

**Comment by kainosnoema** [comment]
@vemonet @gomjellie can this be wrapped up and released? Seems like this project may have been abandoned?

**Comment by vemonet** [comment]
@kainosnoema a month ago I sent an email to Missive, the company responsible for this repo, to ask them about their plan for the future. I did not get an answer yet

This repository is used by many projects, and it is in a pretty good shape, it would be a shame to let it go to waste. 

On my fork I have added some scripts to easily update emojis to newer versions, it should not be hard to maintain

I don't have much time right now, but I am considering to create a maintained fork later this year if nothing has changed, let me know if you would be interested in helping!

**Review by EtienneLem — APPROVED** [review]

**Comment by EtienneLem** [comment]
Sorry for the delay; thanks for submitting the PR @vemonet 🤘🏼

**Comment by forresto** [comment]
15 doesn't show as an option here yet, FYI https://missiveapp.com/open/emoji-mart

**Comment by eggplants** [comment]
`emojiVersion` Choices and Description in `Options / Props` section have to be updated.

https://github.com/missive/emoji-mart/blob/16978d04a766eec6455e2e8bb21cd8dc0b3c7436/README.md?plain=1#L103

**Pull request merged**
