### PR TITLE
Feature/replace webpack tasks on babel

### PR DESCRIPTION
**Pull request by Muffassa**
Ref: #105 
I saved webpack for `build:example` and `test` tasks.

### CODE REVIEW

**Comment by shaypeleg1** [comment]
What's the bundle size now after build?

**Comment by Muffassa** [comment]
@shaypeleg1 107.25 KB

**Comment by ai** [comment]
@Muffassa you forget to remove `webpack` from dependencies and remove unnecessary build scripts.

Also can you post here `npx size-limit --why` result? To be sure that PropTypes was removed.

**Comment by Muffassa** [comment]
@ai Removed unnecessary build scripts. I tried remove `webpack`, but it required for building example build and running test.

**Comment by ai** [comment]
@Muffassa at least you can remove `webpack-bundle-analyzer` since `size-limit --why` does the same

**Comment by Muffassa** [comment]
@ai done

**Comment by EtienneLem** [comment]
Awesome, thanks @Muffassa for contributing 🤘

**Comment by sonicdoe** [comment]
I’m not sure I fully understand the reasoning behind removing `propTypes` in the build. As far as I can tell, I’ll now no longer benefit from `propTypes` during development. Shouldn’t [babel-plugin-transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types) only be used by the application developer when doing a production build?

**Comment by ai** [comment]
@sonicdoe theoretically, yes. But in practice, many developers don’t know about this `babel-plugin-transform-react-remove-prop-types`. We can add it to docs, but users don’t read docs.

But if type checking is really important, we can move this babel plugin to docs.

**Pull request merged**
