### PR TITLE
quick filter: filter emojis by gender. No more duplicates.

### PR DESCRIPTION
**Pull request by phischdev**
Adds a small toolbox below the search bar to quickly filter shown emojis by gender and skin tone.

No more pollution by multiple almost identical male, female, ungendered emojis. (Sections "Recent" and "Search" are left unaffected).

The implementation mirrors that of changing skin tone. QuickFilter can be turned off and on via a single property (`showFilter={true}`).

**polluted "people"-section:**
emojis-pollution

**display male emojis:**
emoji-filter-male
**display female emojis:**
emoji-filter-female
**change skin tone:**
quickfilter3

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks for the PR! Could you explain a bit more about how this might be configurable, for those folks who prefer the existing behavior? Also the tests seem to be failing due to `yarn prettier` not having been run.

**Comment by phischdev** [comment]
Hey Nolan,
Sorry for the late reply and thanks for your interest.

The normal behavior is still default and the quickFilter can be turned on by a property of the same name. Here is the example from the storyboard: `quickFilter={boolean('Quick Filter', true)}`.

Regarding the prettier: I had some problems running it on Windows. In the end also the untouched master branch failed the prettier, so I gave up. Now I'm working on Linux again and ran the prettier. Only thing is it prettified some different file than suggested by Travis. Maybe you can give me a hint.

**Comment by nolanlawson** [comment]
@phischdev You may want to try running on Windows Subsystem for Linux. Admittedly we have not really tried to make this project run well under Windows. `yarn prettier` should fix most issues.

As for what this PR is accomplishing, I'm confused about this statement:

> No more pollution by multiple almost identical emoji.

I'm also confused as to what "quick filter" actually is. Is it this skin color picker next to the emoji? Having an explanation in the `README` would help explain. (And it's something we would need, if this feature were adopted.) :slightly_smiling_face:

**Comment by phischdev** [comment]
@nolanlawson 
> As for what this PR is accomplishing, I'm confused about this statement:
> 
> > No more pollution by multiple almost identical emoji.

When you scroll through the "Smileys & People" section, you see most emojis twice and some even trice because for many of them there is a female, male and ungendered (mostly either male or female) version. This unnecessary bloats the section and makes it hard to find the desired emoji.

> I'm also confused as to what "quick filter" actually is.

QuickFilter ist the thing you see on the pictures I provided in this PR below the search bar.
You can filter those Emojis by gender (showing either male or female version, not showing ungendered version) and I also added the skin tone filter there.

**Comment by phischdev** [comment]
@nolanlawson 
> I'm also confused as to what "quick filter" actually is. Is it this skin color picker next to the emoji? Having an explanation in the README would help explain.

I updated my [inital description](https://github.com/missive/emoji-mart/pull/380#issue-344681081) to make it clearer what I wanted to accomplish. 
Also included description in README.md

**Comment by EtienneLem** [comment]
Thanks a lot for your contribution. [v5.0.0](https://github.com/missive/emoji-mart/discussions/573) has been released and this doesn’t apply anymore.

**Pull request closed without merging**
