### PR TITLE
Add Support for React SSR (fixes #7)

### LINKED ISSUE #7: Support for React SSR
Hi, nice component, but it does not seem to work with React server-side rendering, as it uses the `window` object, which is only available on the client.

	ReferenceError: window is not defined
	  at Object.get (/node_modules/emoji-mart/dist/emoji-mart.js:919:28)
	  at Object.defineProperty.value (/node_modules/emoji-mart/dist/emoji-mart.js:865:35)
	  at __webpack_require__ (/node_modules/emoji-mart/dist/emoji-mart.js:30:30)
	  at Object.defineProperty.value (/node_modules/emoji-mart/dist/emoji-mart.js:609:20)
	  at __webpack_require__ (/node_modules/emoji-mart/dist/emoji-mart.js:30:30)
	  at Object.defineProperty.value (/node_modules/emoji-mart/dist/emoji-mart.js:116:18)
	  at __webpack_require__ (/node_modules/emoji-mart/dist/emoji-mart.js:30:30)
	  at Object.defineProperty.value /node_modules/emoji-mart/dist/emoji-mart.js:64:20)
	  at __webpack_require__ (/node_modules/emoji-mart/dist/emoji-mart.js:30:30)
	  at Object.defineProperty.value (/node_modules/emoji-mart/dist/emoji-mart.js:50:18)

### PR DESCRIPTION
**Pull request by gbhrdt**
This PR makes it possible to run this code on the server side.

### CODE REVIEW

**Comment by EtienneLem** [comment]
Thanks for the PR! I’ve been away for the past 2 weeks and haven’t had the time to review it yet. Will do so ASAP.

**Comment by gbhrdt** [comment]
@EtienneLem any update on this?

**Comment by EtienneLem** [comment]
Sorry for the delay. While I didn’t use the PR as-is, it was really helpful and I based the fix around it, so thanks for that! See https://github.com/missive/emoji-mart/commit/f31a359f782c91bf93cf21d846f2d165038856ff for my version.

**Comment by gbhrdt** [comment]
Alright, thanks!

**Pull request closed without merging**
