### PR TITLE
Package size reduced from 87.35 KB to 79.43 KB

### PR DESCRIPTION
**Pull request by bniwredyc**

### CODE REVIEW

**Comment by ai** [comment]
@bniwredyc can you show `size-limit --why` results? Did we remove all `core-js`?

**Comment by ai** [comment]
@EtienneLem are you OK with updating webpack? (I think latest webpack is always better)

**Comment by bniwredyc** [comment]
@ai you mean this picture?
image

and yes, no core-js left.
The thing is that babel uses core-js to polyfill some of es2015 features e.g. Symbols.
To do to it babel requires `typeof` helper:
image
 which in its turn requires core-js module:
image

Also there were other cases where core-js was required, but I replaced babel helpers to less complex ones (e.g. without support of defineProperty for IE8).

**Comment by ai** [comment]
Great!

@EtienneLem this PR is last part of size optimization, which I promised you

**Comment by EtienneLem** [comment]
Thanks both of you. I want to do a thorough review before merging, but after that I’ll finally be ready to prepare a new release!

**Comment by EtienneLem** [comment]
Everything seems to be working, I’m however getting this size:
screen shot 2017-09-25 at 9 17 09 pm

Did I miss something? 🤔

**Comment by ai** [comment]
Can you show `size-limit --why` output?

**Comment by bniwredyc** [comment]
Confirmed, something went wrong. I think I modified something inside `node_modules` and forgot about it. Will fix it soon. Sorry.

**Comment by bniwredyc** [comment]
Found the problem: I indeed modified the babel's `typeof` helper (used for the `Symbol` support) inside `node_modules`.
So, to disable `typeof` transformation, I replaced es2015 preset with a set of its plugins without `transform-es2015-typeof-symbol`.
Double-checked a clean repository clone - everything seems to be working now.
https://github.com/missive/emoji-mart/pull/113/commits/c8d736de0ae9d68208a022ec114a1f3ff8c93cba

**Comment by ai** [comment]
=^_^= waiting for release

**Pull request merged**
