### PR TITLE
Add virtual list support using react-window

### PR DESCRIPTION
**Pull request by sayjeyhi**
This PR is adding virtual list support.

all features seem to be working. but the sticky category label will be missed

### CODE REVIEW

**Comment by yannterzi** [comment]
@EtienneLem si tu as un peu de temps, cette PR est pas mal importante pour réduire l'impact de performance sur nos projets

**Comment by smatt989** [comment]
why hasn't this been merged yet?

**Comment by hoangvu12** [comment]
Works great, but still got some error like this

image

**Comment by sayjeyhi** [comment]
@hoangvu12 I don't have that bug, which OS and browser you are facing that bug? also can you give a repo to reproduce that issue?

**Comment by hoangvu12** [comment]
> @hoangvu12 I don't have that bug, which OS and browser you are facing that bug? also can you give a repo to reproduce that issue?

I'm using Opera GX and Windows 10. Sorry I don't have any repo to reproduce it.

**Comment by hoangvu12** [comment]
image
This is how it looks like in Microsoft Edge

image
I noticed that the `li` tag is empty. Maybe it is failed to get html?

**Comment by sayjeyhi** [comment]
Well, I think you are using native emoji, and some emojis are not visible there, so a quick solution could be using those emoji sprites, like `apple`, `google`, or other emoji sets.

**Comment by hoangvu12** [comment]
> Well, I think you are using native emoji, and some emojis are not visible there, so a quick solution could be using those emoji sprites, like `apple`, `google`, or other emoji sets.

No I'm currently using `facebook` set.

**Comment by sayjeyhi** [comment]
so can you check why that specific emojis are not loading? check with CSS background

**Comment by hoangvu12** [comment]
> so can you check why that specific emojis are not loading? check with CSS background

It doesn't has any child element that use CSS background
image

**Comment by sayjeyhi** [comment]
well this seems to be another issue, and I think it has nothing to do with the virtual scroll 🤔

**Comment by hoangvu12** [comment]
It only happens in that emoji category, I haven't tried another set yet and other emojis working just fine.
Also, I have a live demo, do you want to check it out?

**Comment by EtienneLem** [comment]
Thanks a lot for your contribution. [v5.0.0](https://github.com/missive/emoji-mart/discussions/573) has been released and this doesn’t apply anymore. The new version should handle an infinite (give or take) amount of emojis.

**Pull request closed without merging**
