### PR TITLE
feat: Add Dark Mode

### PR DESCRIPTION
**Pull request by nolanlawson**
Rebased and squashed version of the dark mode PR: #374

### CODE REVIEW

**Comment by nolanlawson** [comment]
Also added documentation for dark mode

**Comment by rugk** [comment]
BTW: You can (automatically) [let issues close](https://help.github.com/articles/closing-issues-via-commit-messages/) when a PR is merged by adding some "magic" text to your PR _body_.

**Comment by EtienneLem** [comment]
Nice! Updated the UI a bit, namely: borders color and color picker background.

Screen Shot 2019-12-23 at 9 22 21 AM

**Comment by rugk** [comment]
BTW in your Changelog,/commit this "feat[ure]" got converted into a simple "fix", https://github.com/missive/emoji-mart/commit/8cff39f6fd7add3a15ba7695bc117fe4794d3688 … well… I guess this was unintended :smile:

**Comment by santoshnaagula** [comment]
[darkMode]="false"

**Pull request merged**
