### PR TITLE
Allow picker to display emoji natively

### PR DESCRIPTION
**Pull request by tracker-common**
Allow picker to display emojis native rather than just through the sprite sheet.

### CODE REVIEW

**Comment by EtienneLem** [comment]
Just a note: Haven’t forgotten about that PR, I would really love to have that in EmojiMart. Last time I tried, there was some layout issues (namely when hovering the emojis) when using native emojis in the picker.

That being said, I haven’t gotten around to checking with your changes. Will try to do that very soon!

**Comment by tracker-common** [comment]
@EtienneLem - no worries.  Downloading the image sprite sheet was too slow for our product, so I think this will be a good addition.  There was a css change that I probably should have submitted to make the layout better.  Chrome doesn't kern emojis correctly, so in our css we had to add this to make the circle'd highlights better.  

.emoji-mart .emoji-mart-emoji {
  padding: 6px;
  cursor: pointer;
  width: 32px;
}

**Comment by ELD** [comment]
@EtienneLem Had a chance to look at this yet? Just pinging this PR again. We'd love to have this merged upstream.

**Comment by ELD** [comment]
@EtienneLem Just noticed this one had a merge conflict from the previous PRs. I can resolve the conflict in the next hour or so and then you can decide to merge or not.

**Comment by EtienneLem** [comment]
No worries, I can resolve it. Got to check the CSS too. You could however either [give me access](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) to the PR or I can merge manually w/ my changes.

**Comment by ELD** [comment]
It looks like the "allow edits from maintainers" box is checked on the original PR, so you should have access to modify it.

**Comment by EtienneLem** [comment]
Looks great on my end, thanks so much! 🤘

**Pull request merged**
