### PR TITLE
Adding Persian localization into the project

### PR DESCRIPTION
**Pull request by abolfazl-talaei**
I just added necessary changes required for having Persian localization in project.
Could you please consider reviewing my work.
Thank you.

### CODE REVIEW

**Comment by abolfazl-talaei** [comment]
Hi @EtienneLem
Is opening a pull request for adding new localization (Persian in this case) ok without any related issue in the issues part? And would be this merged into the main branch?
Thanks

**Comment by EtienneLem** [comment]
Sure thing! New locale PRs will be reviewed and merged soon.

**Comment by EtienneLem** [comment]
Thanks for the contribution. Am I right that Persian is a RTL (right-to-left) script? Should it be reflected in the UI where the categories checkpoint would be right aligned?

**Comment by abolfazl-talaei** [comment]
Thanks @EtienneLem
That's true, Persian is a RTL language and it should be reflected in the UI. Could you please help me how I should change that? With the help of css?

**Comment by EtienneLem** [comment]
No worries, got it covered!

با تشکر!

**Pull request merged**
