### PR TITLE
Added `type={"button"}` to anchors.js

### PR DESCRIPTION
**Pull request by The-Code-Monkey**
without this it will submit the form if you are within a redux form with react not sure about other libraries but the button doesn't seem to need to not have this type attribute

### CODE REVIEW

**Comment by The-Code-Monkey** [comment]
i can confirm this fixes the issue and doesn't break any functionailty

**Comment by The-Code-Monkey** [comment]
@missive can we merge this please really affecting a project that im currently working on and cannot edit node_modules every time i add something

**Comment by EtienneLem** [comment]
Yes of course, sorry for the delay and thanks for the patch!

**Comment by EtienneLem** [comment]
`v2.11.1` has just been released.

**Pull request merged**
