### PR TITLE
Add support for more than one custom category

### LINKED ISSUE #224: Add support for more than one custom category
i will accept some others categories, How can I create not only one custom category?

### PR DESCRIPTION
**Pull request by Gargron**
Fix #224

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks for the PR! Can you confirm that this isn't a breaking change, and could you add some docs to the README to explain how to use this new feature?

I ran the tests manually and they passed, although a new test wouldn't hurt either. :)

**Comment by nolanlawson** [comment]
Added some tests to confirm that this isn't a breaking change (if you don't specify `customCategory`, then the behavior is the same as before), and added a test and storybook for custom category as well as docs.

**Comment by nolanlawson** [comment]
Storybook with custom categories shown:

Screenshot from 2019-12-21 10-21-31

**Comment by lilong7676** [comment]
Thank you. Two questions:
How do I move a custom item to the front?
How to customize the width and height of the emoji icon?

@Gargron

**Pull request merged**
